# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'python:3.5'

# The build-time dependencies of the app.
dependencies:
    python:
       rasa_core: '*'
       rasa_nlu: '*'
hooks:
  build: |
      if [ ! -f data/total_word_feature_extractor.dat ]; then
        cwd=$(pwd)
        cd /tmp
        wget https://github.com/mit-nlp/MITIE/releases/download/v0.4/MITIE-models-v0.2.tar.bz2
        tar jxf MITIE-models-v0.2.tar.bz2
        mkdir -p $cwd/data
        mv MITIE-models/english/total_word_feature_extractor.dat $cwd/data/total_word_feature_extractor.dat
      fi
    
# The configuration of app when it is exposed to the web.
web:
    # Commands are run once after deployment to start the application process.
    commands:
       start: "python -m rasa_nlu.server -e wit -P $PORT -c config.json"

# The size of the persistent disk of the application (in MB).
disk: 4000
mounts:
   "/logs": "shared:files/logs"
   "/projects": "shared:files/projects"